# DO  modify this file!  It was NOT generated by ‘nixos-generate-config’
# This file was tweaked especially such that it would work on VULTR
# we did _not_ autogenerate it. I repeat. NOT.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_blk" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/vda2";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  nix.maxJobs = 1;
}
